server:
  port: 8081
spring:
  application:
    name: iams
  datasource:
    url: jdbc:mysql://localhost:3306/iams?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8&nullCatalogMeansCurrent=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
knife4j:
  production: true
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    root: info
    com.iams: debug